version: '3'

services:
  elasticsearch:
    image: elasticsearch:7.16.3
    container_name: elasticsearch
    environment:
      - ELASTIC_PASSWORD=mysecretpassword
      - ELASTIC_USERNAME=elastic
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - ./elasticsearch-data:/usr/share/elasticsearch/data

  kibana:
    image: kibana:7.16.3
    container_name: kibana
    environment:
      - KIBANA_HOST=elasticsearch
      - KIBANA_PORT=5601
      - KIBANA_USERNAME=elastic
      - KIBANA_PASSWORD=mysecretpassword
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"

  logstash:
    image: logstash:7.16.3
    container_name: logstash
    environment:
      - LOGBACK_HOST=elasticsearch
      - LOGBACK_PORT=5000
      - LOGBACK_USERNAME=elastic
      - LOGBACK_PASSWORD=mysecretpassword
    depends_on:
      - elasticsearch